export const LOGIN_SUCCESS="lOGIN_SUCCESS";
export const LOGIN_FAIL="lOGIN_FAIL";
export const LOAD_USER_SUCCESS="lOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE="lOAD_USER_FAILURE";
export const AUTHENTICATION_SUCCESS="AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE="AUTHENTICATION_FAILURE";
export const LOG_OUT="LOG_OUT";
export const PASSWORD_RESET_SUCCESS="PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILURE="PASSWORD_RESET_FAILURE";
export const PASSWORD_RESET_CONFIRM_SUCCESS="PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAILURE="PASSWORD_RESET_FAILURE";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGNUP_FAILURE="SIGNUP_FAILURE";
export const ACTIVATION_SUCCESS="ACTIVATION_SUCCESS";
export const ACTIVATION_FAILURE="ACTIVATION_FAILURE";

